### ISSUE TITLE
how to get the image generator weight?

### ISSUE THREAD

**Issue by Zhaoyisong** [jamesli1618/Obj-GAN#3]

**Comment by Zhaoyisong** [comment]
Could you please explain How to Train Image Generator Weight with Coco Data Set? 
Thanks!

**Comment by jamesli1618** [comment]
Thanks a lot for your interests. We have achieved several updates for the model, the latest model is still under training. We will release the checkpoint of image generator in 2 weeks from now on.

**Comment by Zhaoyisong** [comment]
> Thanks a lot for your interests. We have achieved several updates for the model, the latest model is still under training. We will release the checkpoint of image generator in 2 weeks from now on.
T

> Thanks a lot for your interests. We have achieved several updates for the model, the latest model is still under training. We will release the checkpoint of image generator in 2 weeks from now on.

Thanks!

**Comment by Zhaoyisong** [comment]
> Thanks a lot for your interests. We have achieved several updates for the model, the latest model is still under training. We will release the checkpoint of image generator in 2 weeks from now on.
T

> Thanks a lot for your interests. We have achieved several updates for the model, the latest model is still under training. We will release the checkpoint of image generator in 2 weeks from now on.

Thanks!

**Comment by Zhaoyisong** [comment]
> Thanks a lot for your interests. We have achieved several updates for the model, the latest model is still under training. We will release the checkpoint of image generator in 2 weeks from now on.

Thanks!
