### ISSUE TITLE
Missing nms_cuda.c while executing make.sh in image_generation

### ISSUE THREAD

**Issue by joeyy5588** [jamesli1618/Obj-GAN#4]
While running `make.sh`, I'm getting a `no such file or directory` error for the file `nms_cuda.c`. This
appears to be missing from the `image_generation/model/nms/src` directory.
I assume it's the same src file located here:
[faster-rcnn.pytorch/lib/model/nms/src/nms_cuda.c](https://github.com/jwyang/faster-rcnn.pytorch/blob/master/lib/model/nms/src/nms_cuda.c)

**Comment by jamesli1618** [comment]
Thanks for pointing out this bug. I did not find it because nms is not used in our code. The modules related to faster-rcnn is borrowed from Jianwei's repo, and the only module from his repo being used here is the ROI Align.
