### ISSUE TITLE
Code Question

### ISSUE THREAD

**Issue by AmingWu** [jamesli1618/Obj-GAN#5]
Hello,
When I run python sample.py --is_training 1, the result is as: 

![QQ截图20190702153039](https://user-images.githubusercontent.com/38445175/60493285-18d89d00-9cdf-11e9-9dd6-eafdb0378575.jpg)

Is the result right?

**Comment by QLMX** [comment]
I get the same problem

**Comment by jamesli1618** [comment]
This problem is common when I trained the box generator. We'd better monitor the training process. According to my experiences, 10% progress is already enough for the generation. Any suggestions for improving the training stability is welcomed. Thanks.

**Comment by QLMX** [comment]
When code runs to 10%, stop manually?

**Comment by QLMX** [comment]
> This problem is common when I trained the box generator. We'd better monitor the training process. According to my experiences, 10% progress is already enough for the generation. Any suggestions for improving the training stability is welcomed. Thanks.

When code runs to 10%, stop manually?

**Comment by jamesli1618** [comment]
You got the real meaning of monitoring. There is an argument named "num_epochs" in "train" function to control the length of the progress.
