### ISSUE TITLE
undefined symbol: PyFPE_jbuf

### ISSUE THREAD

**Issue by konnnnnn** [jamesli1618/Obj-GAN#6]
When samlping shape_generator, such error occurs.
![image](https://user-images.githubusercontent.com/52525995/60935044-17b8f880-a2fb-11e9-92e4-348e4cac690a.png)
I have maked sure that LD_LIBRARY_PATH is added.
So could you please tell me what to try?

**Comment by joeyy5588** [comment]
I've also encountered this problem.
I solved it by doing the following steps:
`$ git clone https://github.com/cocodataset/cocoapi`
`$ cd PythonAPI/`
`$ make`
`$ cd pycocotools`
`$ cp _mask.cpython-36m-x86_64-linux-gnu.so [to your pycocotools path]`

**Comment by konnnnnn** [comment]
Thank you for fast reply!
After executing the make step, _mask.cpython-37m-x86_64-linux-gnu.so is generated instead of _mask.cpython-37m-x86_64-linux-gnu.so. I tried to copy it to my pycocotools path and rename it to 36m but the undefined symbol error still occurs. So should I make changes to _mask.c or other codes? If so , could you please suggest some ways to do that?
![image](https://user-images.githubusercontent.com/52525995/60952681-49978280-a32e-11e9-844c-ed758b937379.png)

**Comment by konnnnnn** [comment]
Thank you for fast reply!
After executing the make step, _mask.cpython-37m-x86_64-linux-gnu.so is generated instead of _mask.cpython-36m-x86_64-linux-gnu.so. I tried to copy it to my pycocotools path and rename it as 36m but the undefined symbol error still occurs. So should I make changes to _mask.c or other codes? If so , could you please suggest some ways to do that?
![image](https://user-images.githubusercontent.com/52525995/60954178-24f0da00-a331-11e9-9f44-48e71117d23b.png)

**Comment by joeyy5588** [comment]
Is it possible that we are using different python version which leads to different name of the file generated?
Mine is 3.6.4
I guess you are using 3.7?

**Comment by konnnnnn** [comment]
I was using python 3.6.8 and after switching to your version the same file can be generated. However, though  _mask.cpython-37m-x86_64-linux-gnu.so seems to work correctly, another error arises with _mask.so. Is there any way to solve this problem? 
![image](https://user-images.githubusercontent.com/52525995/60956178-d7766c00-a334-11e9-8714-1b074ce0c22c.png)

**Comment by joeyy5588** [comment]
I didn't meet this error but maybe you can refer to this:
[https://github.com/cocodataset/cocoapi/issues/90](https://github.com/cocodataset/cocoapi/issues/90)

**Comment by jamesli1618** [comment]
Thanks a lot for your interests. I also encounter similar issues when I launch the experiments on some cloud clusters. However, I can do it on my local machine. Since the COCO package is only useful for generating the data. Therefore, a very simple solution is to generate the data on the local machine, transfer it to the cluster, and then comment the import of COCO out when running on cluster.

**Comment by konnnnnn** [comment]
Thanks for your kindness! I solved this problem by changing every 'python' to 'python3' in the makefile of cocoapi.
